name: trigger_js_package_release # Trigger JS package re-generate and publish to NPM (https://github.com/haimkastner/unitsnet-js)

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call re-run generate & publish job 
        env:
          UNITISNET_JS_WORKFLOW_TOKEN: ${{ secrets.UNITISNET_JS_WORKFLOW_TOKEN }}
        run: |
          # Fetch all unitsnet-js jobs
          jobs=$(curl --location --request GET "https://api.github.com/repos/haimkastner/unitsnet-js/actions/runs" --header "Accept: application/vnd.github+json" --header "Authorization: Bearer $UNITISNET_JS_WORKFLOW_TOKEN")
          # Extract the latest master job id
          latest_prod_job=$(echo $jobs | jq -r '.workflow_runs[] | select(.head_branch=="master") | .id' |  head -n 1)
          # Re-run it, to re-generate and publish a new package version
          echo $latest_prod_job
